from gturtle import *
import backgrounds

def a1(pTurtle):
    pTurtle.setPenColor("white")
    pTurtle.setPenWidth(5)
    pTurtle.hideTurtle()
    for i in range(24):
        pTurtle.fd(10*i)      
        pTurtle.bk(10*i*2)
        pTurtle.fd(10*i)
        delay(50)
        pTurtle.rt(15)
    delay(80)
    pTurtle.setFillColor("black")
    pTurtle.fill()
    backgrounds.fight(pTurtle)
    
def a2(pTurtle):
    pTurtle.setHeading(180)
    pTurtle.setPenColor("red")
    pTurtle.setFillColor("black")
    pTurtle.setPenWidth(140)
    repeat 2:
        pTurtle.bk(110)
        pTurtle.fd(220)
        pTurtle.bk(110)
        delay(500)
        pTurtle.setPenColor("white")
    pTurtle.fill()
    backgrounds.fight(pTurtle)
    
def a3(pTurtle):
    pTurtle.setPenColor("white")
    pTurtle.setPos(-100,-180)
    pTurtle.setHeading(20)
    repeat 100:
        pTurtle.fd(4)
    pTurtle.setPos(25,-178)
    pTurtle.setHeading(-25)
    repeat 100:
        pTurtle.fd(4)
    pTurtle.setPos(-150,-100)
    pTurtle.setHeading(69)
    repeat 100:
        pTurtle.fd(4)
    pTurtle.setPos(150,-10)
    pTurtle.setHeading(-56)
    repeat 100:
        pTurtle.fd(4)
    pTurtle.setPos(-200,-50)
    pTurtle.setHeading(90)
    pTurtle.setPenWidth(60)
    repeat 20:
        pTurtle.fd(18)
    pTurtle.setPos(-200,60)
    pTurtle.setHeading(90)
    pTurtle.setPenWidth(60)
    repeat 20:
        pTurtle.fd(18)
    delay(200)
    backgrounds.fight(pTurtle)
    
def a4(pTurtle):
    pTurtle.setPenColor("white")
    pTurtle.setPenWidth(5)
    for i in range(4):
        pTurtle.setPos(-100+i*50,-100+i*50)
        repeat 25:
            pTurtle.fd(43)
            pTurtle.lt(53)
            pTurtle.bk(69)
            delay(10)
    backgrounds.fight(pTurtle)
        
def a5(pTurtle):
    backgrounds.fight(pTurtle)
    pTurtle.setFillColor("black")
    pTurtle.setPenColor("red")
    pTurtle.setPenWidth(120)
    pTurtle.setPos(-140,-80)
    pTurtle.setHeading(90)
    pTurtle.fd(280)
    delay(600)
    backgrounds.fight(pTurtle)
    pTurtle.setPenColor("white")
    pTurtle.setPenWidth(120)
    pTurtle.setPos(-140,-80)
    pTurtle.setHeading(90)
    pTurtle.fd(280)
    delay(600)
    backgrounds.fight(pTurtle)
    pTurtle.setPenColor("red")
    pTurtle.setPenWidth(120)
    pTurtle.setPos(-140,80)
    pTurtle.setHeading(90)
    pTurtle.fd(280)
    delay(600)
    backgrounds.fight(pTurtle)
    pTurtle.setPenColor("white")
    pTurtle.setPenWidth(120)
    pTurtle.setPos(-140,80)
    pTurtle.setHeading(90)
    pTurtle.fd(280)
    delay(600)
    
    backgrounds.fight(pTurtle)
    pTurtle.setFillColor("black")
    pTurtle.setPenColor("red")
    pTurtle.setPenWidth(120)
    pTurtle.setPos(-140,-80)
    pTurtle.setHeading(90)
    pTurtle.fd(280)
    delay(600)
    backgrounds.fight(pTurtle)
    pTurtle.setPenColor("white")
    pTurtle.setPenWidth(120)
    pTurtle.setPos(-140,-80)
    pTurtle.setHeading(90)
    pTurtle.fd(280)
    delay(600)
    backgrounds.fight(pTurtle)
    pTurtle.setPenColor("red")
    pTurtle.setPenWidth(120)
    pTurtle.setPos(-140,80)
    pTurtle.setHeading(90)
    pTurtle.fd(280)
    delay(600)
    backgrounds.fight(pTurtle)
    pTurtle.setPenColor("white")
    pTurtle.setPenWidth(120)
    pTurtle.setPos(-140,80)
    pTurtle.setHeading(90)
    pTurtle.fd(280)
    delay(600)
    
    backgrounds.fight(pTurtle)
    pTurtle.setPenColor("red")
    pTurtle.setPenWidth(200)
    pTurtle.setPos(-140,0)
    pTurtle.setHeading(90)
    pTurtle.fd(280)
    delay(600)
    backgrounds.fight(pTurtle)
    pTurtle.setPenColor("white")
    pTurtle.setPenWidth(200)
    pTurtle.setPos(-140,0)
    pTurtle.setHeading(90)
    pTurtle.fd(280)
    delay(600)
    backgrounds.fight(pTurtle)

def a5v2(pTurtle):
    backgrounds.fight(pTurtle)
    pTurtle.setFillColor("black")
    pTurtle.setPenColor("red")
    pTurtle.setPenWidth(120)
    pTurtle.setPos(-140,-80)
    pTurtle.setHeading(90)
    pTurtle.fd(280)
    delay(200)
    backgrounds.fight(pTurtle)
    pTurtle.setPenColor("white")
    pTurtle.setPenWidth(120)
    pTurtle.setPos(-140,-80)
    pTurtle.setHeading(90)
    pTurtle.fd(280)
    delay(200)
    backgrounds.fight(pTurtle)
    pTurtle.setPenColor("red")
    pTurtle.setPenWidth(120)
    pTurtle.setPos(-140,80)
    pTurtle.setHeading(90)
    pTurtle.fd(280)
    delay(200)
    backgrounds.fight(pTurtle)
    pTurtle.setPenColor("white")
    pTurtle.setPenWidth(120)
    pTurtle.setPos(-140,80)
    pTurtle.setHeading(90)
    pTurtle.fd(280)
    delay(200)
    
    backgrounds.fight(pTurtle)
    pTurtle.setFillColor("black")
    pTurtle.setPenColor("red")
    pTurtle.setPenWidth(120)
    pTurtle.setPos(-140,-80)
    pTurtle.setHeading(90)
    pTurtle.fd(280)
    delay(200)
    backgrounds.fight(pTurtle)
    pTurtle.setPenColor("white")
    pTurtle.setPenWidth(120)
    pTurtle.setPos(-140,-80)
    pTurtle.setHeading(90)
    pTurtle.fd(280)
    delay(200)
    backgrounds.fight(pTurtle)
    pTurtle.setPenColor("red")
    pTurtle.setPenWidth(120)
    pTurtle.setPos(-140,80)
    pTurtle.setHeading(90)
    pTurtle.fd(280)
    delay(200)
    backgrounds.fight(pTurtle)
    pTurtle.setPenColor("white")
    pTurtle.setPenWidth(120)
    pTurtle.setPos(-140,80)
    pTurtle.setHeading(90)
    pTurtle.fd(280)
    delay(200)
    
    backgrounds.fight(pTurtle)
    pTurtle.setPenColor("red")
    pTurtle.setPenWidth(200)
    pTurtle.setPos(-140,0)
    pTurtle.setHeading(90)
    pTurtle.fd(280)
    delay(140)
    backgrounds.fight(pTurtle)
    pTurtle.setPenColor("white")
    pTurtle.setPenWidth(200)
    pTurtle.setPos(-140,0)
    pTurtle.setHeading(90)
    pTurtle.fd(280)
    delay(140)
    backgrounds.fight(pTurtle)

def a6(pTurtle):
    pTurtle.setPenColor("white")
    pTurtle.setPenWidth(6)
    pTurtle.setPos(-180,-180)
    pTurtle.setHeading(69)
    for i in range(80):
        pTurtle.setPos(-180+i*10,-50)
        if i %2:
            pTurtle.rt(69)
            pTurtle.fd(240)
        else:
            pTurtle.lt(89)
            pTurtle.fd(240)
    backgrounds.fight(pTurtle)
    delay(600)

def a7(pTurtle):
    pTurtle.setPenColor("white")
    pTurtle.setPenWidth(5)
    pTurtle.setHeading(271)
    pTurtle.setPos(0,-230)
    for i in range(360):
        pTurtle.fd(4)
        pTurtle.rt(1)
        if i%17 == 0:
            pTurtle.rt(90)
            pTurtle.fd(450)
            pTurtle.bk(450)
            pTurtle.lt(90)
        delay(4)
    backgrounds.fight(pTurtle)

def a8(pTurtle):
    pTurtle.setPenColor("white")
    pTurtle.setPenWidth(13)
    pTurtle.setPos(-140,-140)
    pTurtle.setHeading(0)
    repeat 16:
        pTurtle.fd(280)
        pTurtle.bk(280)
        pTurtle.rt(20)
    pTurtle.setPos(140,140)
    pTurtle.setHeading(180)
    repeat 16:
        pTurtle.fd(280)
        pTurtle.bk(280)
        pTurtle.rt(20)
        delay(20)
    backgrounds.fight(pTurtle)

def a9(pTurtle):
    global dlp
    pTurtle.setPenColor("white")
    pTurtle.setPenWidth(280)
    pTurtle.setPos(280,0)
    pTurtle.setHeading(270)
    if dlp < 200:
        repeat 235:
            pTurtle.fd(1)
            delay(30)
        pTurtle.setPenColor("red")
        repeat 65:
            pTurtle.fd(1)
            delay(30)
        delay(6000)
    else:
        repeat 300:
            pTurtle.fd(1)
            delay(30)
        delay(6000)